### ISSUE TITLE
Некорректная страница при входе

### ISSUE THREAD

**Issue by DronB** [xlabsoft/JavaHW#4]
При входе попадает не в свой профиль а в окно с ошибкой

Ходы для воспроизведения:

1)Запуск приложения.
2)Открытие главной страницы.

Ожидаемый результат:
Открытие главной страницы.

Фактический результат:
Ошибка открытия страницы

**Comment by xlabsoft** [comment]
applicationContext & login.jsp - фикс проблемы с логином
