### ISSUE TITLE
При регистрации нового пользователя он не добавляется в базу

### ISSUE THREAD

**Issue by DronB** [xlabsoft/JavaHW#6]
При регистрации нового пользователя он не добавляется в базу

Ходы для воспроизведения:

1)Вход на страницу регистрации.
2)Регистрация пользователя.

Ожидаемый результат:
Добавление нового пользователя в базу.

Фактический результат:
Пользователь не добавляется в базу

**Comment by xlabsoft** [comment]
register.jsp; AccountsController.java; AccountServiceImpl.java - фикс
бага при регистрации
